export const DEFAULT_PROJECTS = [
  {
    id: "myra",
    brand: "Myra",
    title: "Myra",
    fullTitle: "Full Brand Rejuvenation & E-Commerce Scaler",
    index: "01",
    category: "Branding",
    year: "2026",
    location: "COLOMBO, SRI LANKA",
    market: "Sri Lanka & UAE",
    industry: "Beauty & Wellness",
    services: ["Branding", "Social Media", "Campaigns"],
    short_description: "A connected brand and campaign direction designed to make Myra feel coherent across every customer touchpoint while creating a stronger platform for future growth.",
    overview: "A connected brand and campaign direction designed to make Myra feel coherent across every customer touchpoint while creating a stronger platform for future growth.",
    challenge: "Legacy workflows and fragmented brand touchpoints created high customer drop-off before checkout across retail channels.",
    approach: "Unified digital design system, conversion-focused e-commerce storefront, and high-performance Meta creative funnels.",
    deliverables: "Brand direction, social design system, campaign concepts, launch toolkit and performance-ready creative templates.",
    logo: "/images/brands/myra.png",
    image: "/images/brands/myra.png",
    cover_image: "/images/brand-creatives/myra.jpg",
    video: "/images/brand-creatives/myra-newspaper.mp4",
    metrics: ["+240% Sales Growth", "4.8x Ad ROI", "1.2M+ Reach"]
  },
  {
    id: "uneeflow",
    brand: "Uneeflow",
    title: "Uneeflow",
    fullTitle: "Enterprise AI Workflow & Growth Automation",
    index: "02",
    category: "Systems",
    year: "2026",
    location: "DUBAI, UAE",
    market: "UAE & GCC",
    industry: "Enterprise AI & SaaS",
    services: ["Websites", "Systems", "Automation"],
    short_description: "Architecting an end-to-end client acquisition and automated CRM system processing 10k+ leads weekly with zero downtime.",
    overview: "Architecting an end-to-end client acquisition and automated CRM system processing 10k+ leads weekly with zero downtime.",
    challenge: "High manual lead triaging load created response delays and dropped enterprise deal closure rates.",
    approach: "Built custom AI qualifying agent with integrated CRM sync and high-speed multi-step lead onboarding pipelines.",
    deliverables: "Automated CRM architecture, multi-channel lead qualifier, conversion analytics dashboard, API integrations.",
    logo: "/images/brands/uneeflow.png",
    image: "/images/brands/uneeflow.png",
    cover_image: "/images/brand-creatives/uneeflow-creative.jpg",
    metrics: ["10k+ Weekly Leads", "85% Auto-qualification", "0 Downtime"]
  },
  {
    id: "al-fakhir",
    brand: "Al Fakhir",
    title: "Al Fakhir",
    fullTitle: "Luxury Hospitality Digital Transformation",
    index: "03",
    category: "Websites",
    year: "2026",
    location: "RIYADH & JEDDAH, KSA",
    market: "Saudi Arabia",
    industry: "Luxury Hospitality",
    services: ["Branding", "Websites", "Campaigns"],
    short_description: "High-touch guest reservation platform and bespoke brand identity across Riyadh and Jeddah destinations.",
    overview: "High-touch guest reservation platform and bespoke brand identity across Riyadh and Jeddah destinations.",
    challenge: "Heavy reliance on third-party aggregators reduced profit margins and diluted high-end guest brand experience.",
    approach: "Designed bespoke direct-booking portal paired with luxury lifestyle storytelling and VIP guest retention funnels.",
    deliverables: "Custom reservation web system, Arabic/English multilingual UI, premium photo & video asset suite.",
    logo: "/images/brands/al-fakhir.png",
    image: "/images/brands/al-fakhir.png",
    cover_image: "/images/brand-creatives/al-fakhir.jpg",
    metrics: ["+180% Direct Bookings", "99.9% Uptime", "4.9★ Rating"]
  },
  {
    id: "hijaz",
    brand: "Hijaz",
    title: "Hijaz",
    fullTitle: "Gourmet FMCG Brand Expansion & Digital Retail",
    index: "04",
    category: "Branding",
    year: "2026",
    location: "KANDY, SRI LANKA",
    market: "Sri Lanka",
    industry: "Gourmet FMCG",
    services: ["Branding", "Social Media", "Campaigns"],
    short_description: "Packaging overhaul, nationwide social media blitz, and automated distributor portal accelerating retail growth.",
    overview: "Packaging overhaul, nationwide social media blitz, and automated distributor portal accelerating retail growth.",
    challenge: "Outdated packaging aesthetics and fragmented distributor ordering limited nationwide distribution efficiency.",
    approach: "Full retail packaging redesign, high-impact influencer food campaigns, and digital distributor portal.",
    deliverables: "Packaging design series, distributor management web app, social content library, point-of-sale retail creative.",
    logo: "/images/brands/hijaz-logo.png",
    image: "/images/brands/hijaz-logo.png",
    cover_image: "/images/brand-creatives/hijaz_pasta.jpg",
    video: "/images/brand-creatives/hijaz-ad.mp4",
    metrics: ["+310% Retail Orders", "2.5M Impressions", "50+ Distributors"]
  },
  {
    id: "mahanama",
    brand: "Mahanama",
    title: "Mahanama",
    fullTitle: "Educational Institution Platform & Identity",
    index: "05",
    category: "Websites",
    year: "2026",
    location: "GALLE, SRI LANKA",
    market: "Sri Lanka",
    industry: "Education & Training",
    services: ["Websites", "Branding", "Campaigns"],
    short_description: "Bespoke modern educational portal and student onboarding campaigns driving institutional leadership.",
    overview: "Bespoke modern educational portal and student onboarding campaigns driving institutional leadership.",
    challenge: "Paper-based student admissions and outdated web presence slowed down semester intake processing.",
    approach: "Engineered student self-service application portal with automated document verification and admission campaigns.",
    deliverables: "Responsive student admissions platform, institutional brand guidelines, social campaign launch kit.",
    logo: "/images/brands/mahanama.png",
    image: "/images/brands/mahanama.png",
    cover_image: "/images/brand-creatives/mahanama.jpg",
    metrics: ["+150% Enrollment", "98% Positive Feedback", "50k+ Visitors"]
  },
  {
    id: "lucky-darbar",
    brand: "Lucky Darbar",
    title: "Lucky Darbar",
    fullTitle: "Culinary Brand Experience & Social Growth",
    index: "06",
    category: "Branding",
    year: "2026",
    location: "NEGOMBO, SRI LANKA",
    market: "Sri Lanka & India",
    industry: "Gourmet Dining Chain",
    services: ["Branding", "Social Media", "Campaigns"],
    short_description: "Full culinary brand identity, menu architecture, and viral social campaigns increasing restaurant footfall.",
    overview: "Full culinary brand identity, menu architecture, and viral social campaigns increasing restaurant footfall.",
    challenge: "Competitive regional dining market required distinctive positioning to drive repeat customer footfall.",
    approach: "Crafted authentic heritage visual identity, sensory food videography, and geo-targeted social activations.",
    deliverables: "Brand identity system, physical and digital menu designs, video reels library, geo-fenced social ad campaigns.",
    logo: "/images/brands/lucky-darbar.png",
    image: "/images/brands/lucky-darbar.png",
    cover_image: "/images/brand-creatives/lucky-darbar.jpg",
    metrics: ["+220% Footfall", "3.5x ROI", "800k+ Reach"]
  },
  {
    id: "crane-shoes",
    brand: "Crane Shoes",
    title: "Crane Shoes",
    fullTitle: "Footwear & Lifestyle E-Commerce Store",
    index: "07",
    category: "Websites",
    year: "2026",
    location: "CHENNAI, INDIA",
    market: "India",
    industry: "Retail & Footwear",
    services: ["Websites", "Branding", "Social Media"],
    short_description: "High converting lifestyle retail portal and influencer campaign series scaling direct-to-consumer sales.",
    overview: "High converting lifestyle retail portal and influencer campaign series scaling direct-to-consumer sales.",
    challenge: "Low mobile checkout conversion rates on legacy store restricted direct-to-consumer sales velocity.",
    approach: "Re-architected lightning-fast mobile-first e-commerce checkout with dynamic sizing guides and social proof.",
    deliverables: "Custom storefront development, inventory sync pipelines, product photography direction, influencer lookbooks.",
    logo: "/images/brands/crane-shoes.png",
    image: "/images/brands/crane-shoes.png",
    cover_image: "/images/brand-creatives/crane-shoes.jpg",
    metrics: ["+190% Conversion Rate", "350ms Page Speed", "40k+ Pairs Sold"]
  },
  {
    id: "fly-bagdad",
    brand: "Fly Bagdad",
    title: "Fly Bagdad",
    fullTitle: "Aviation Portal & Performance Acquisition",
    index: "08",
    category: "Automation",
    year: "2026",
    location: "BAGHDAD, IRAQ",
    market: "Iraq & MENA",
    industry: "Aviation & Travel",
    services: ["Websites", "Campaigns", "Automation"],
    short_description: "Flight booking engine optimization and regional acquisition campaigns expanding market share.",
    overview: "Flight booking engine optimization and regional acquisition campaigns expanding market share.",
    challenge: "Complex legacy ticketing flows led to high abandoned booking carts and costly customer support overhead.",
    approach: "Streamlined passenger reservation UX, automated ticket confirmation workflows, and localized flight promotion engines.",
    deliverables: "Booking portal UI overhaul, automated passenger notification engine, multi-currency payment gateway.",
    logo: "/images/brands/fly-bagdad.png",
    image: "/images/brands/fly-bagdad.png",
    cover_image: "/images/brand-creatives/fly-bagdad.jpg",
    metrics: ["+280% Booking Volume", "65% Cost Per Acquisition", "12 Regional Routes"]
  }
];
