/**
 * All copy for the Products index and the shared labels on every product detail page.
 * Supports 5 languages: en (English), es (Spanish), ar (Arabic), si (Sinhala), ta (Tamil).
 */

export const I18N_PRODUCTS_PAGE = {
  en: {
    breadcrumb: { home: "Home", current: "Products" },
    hero: {
      label: "Our systems",
      title: "Systems that fit the business",
      emphasis: "fit",
      lead: "Working systems Cambridge Marketing builds, deploys and fits to how a business actually trades. Open any one of them and every screen you see is a capture of it running.",
      primaryAction: { href: "/#services", label: "Book a strategy call" },
      secondaryAction: { href: "#catalogue", label: "Explore systems" },
    },
    adaptation: {
      label: "How we are different",
      headingParts: [
        { text: "We fit the " },
        { text: "system to the business", tone: "accent" },
        { text: ", not the " },
        { text: "business to the system", tone: "counter" },
      ],
      body: "Most software asks a business to work the way it was built. That is fine until the fit is wrong, and then it is a daily tax paid by the people at the counter. A till written for a restaurant, put into a shop that sells by weight, is the clearest version of it.",
      genericTitle: "A system built for someone else",
      genericNote: "A restaurant till, running a grocery shop.",
      fittedTitle: "A system built for you",
      fittedNote: "The same job, fitted to how the shop actually trades.",
      unusedLabel: "fields the counter staff skip, every day",
      generic: [
        { field: "Table number", verdict: "unused" },
        { field: "Covers per sitting", verdict: "unused" },
        { field: "Kitchen ticket", verdict: "unused" },
        { field: "Split the bill", verdict: "unused" },
        { field: "Stock counted by portion", verdict: "forced" },
        { field: "Price per item", verdict: "kept" },
      ],
      fitted: [
        { field: "Aisle and shelf", verdict: "kept" },
        { field: "Basket size", verdict: "kept" },
        { field: "Weighed goods", verdict: "kept" },
        { field: "Price by weight", verdict: "kept" },
      ],
    },
    customisation: {
      label: "How they are delivered",
      headingParts: [
        { text: "Every system is " },
        { text: "fitted", tone: "accent" },
        { text: " before it is handed over" },
      ],
      body: "None of these arrives as it is shown here. Each is configured against a real operation, carries the client's own branding rather than ours, and keeps only the parts of the system that business actually uses.",
      points: [
        "Configured against how the business already works, not the other way round",
        "Delivered under the client's own name and identity",
        "Modules the business does not need are taken out rather than hidden",
        "Extended where the operation needs something the system does not do yet",
      ],
    },
    index: {
      label: "Live Reference Systems",
      heading: "Example Systems Built for Real Operations",
      description: "Every system we engineer is fully customized, re-engineered, and tailored to your exact business needs.",
      allLabel: "All",
      filterLabel: "Filter systems by industry",
      singularLabel: "system",
      pluralLabel: "systems",
      inLabel: "in",
      screensLabel: "screens",
    },
    contact: {
      heading: "See it against your own operation.",
      body: "Tell us how the business trades today and we will show the system working against that, rather than against a demo dataset.",
      action: { href: "/#services", label: "Book a strategy call" },
    },
    detail: {
      breadcrumbHome: "Home",
      breadcrumbIndex: "Products",
      demoLabel: "View demo",
      requestDemoLabel: "Book a strategy call",
      documentationLabel: "Documentation",
      sections: {
        solves: {
          label: "What it solves",
          heading: "The operational problem",
        },
        interface: {
          label: "Interface",
          heading: "The system in use",
          captureNote: "Screens are captures of the working system.",
          themeLabel: "Themes",
          themeHeading: "What your contact opens",
          themeNote: "Each card is built to the client's own identity. These are the themes it starts from.",
          illustrationNote: "This system was published with drawn views of its interface rather than photographs of it running, so that is what is shown below.",
        },
        modules: {
          label: "Modules and features",
          heading: "What it handles",
          body: "This is the system's own catalogue. It is deliberately not repeated on the service pages that implement it.",
        },
        replaces: {
          label: "What it replaces",
          heading: "What this takes off the desk",
        },
        adapts: {
          label: "Where we fit it",
          heading: "What gets changed for you",
          body: "None of these is handed over as it is shown above. These are the parts most often fitted to a particular business.",
        },
        suits: {
          label: "Who it suits",
          heading: "The business this is for",
        },
        industriesLabel: "Industries supported",
        integrationsLabel: "Integrations",
        services: {
          label: "Implementation and support",
          heading: "How this system is delivered",
          body: "The work around the system is a service engagement. Each one is described in full on our services section.",
        },
      },
      contact: {
        heading: "See it against your own numbers.",
        body: "Tell us how the business trades today and we will show the system working against that, rather than against a demo dataset.",
        action: { href: "/#services", label: "Book a strategy call" },
      },
    },
  },

  es: {
    breadcrumb: { home: "Inicio", current: "Productos" },
    hero: {
      label: "Nuestros sistemas",
      title: "Sistemas que se ajustan al negocio",
      emphasis: "ajustan",
      lead: "Sistemas operativos que Cambridge Marketing construye, despliega y adapta a la forma en que realmente opera un negocio. Abra cualquiera de ellos y cada pantalla es una captura de su funcionamiento real.",
      primaryAction: { href: "/#services", label: "Reservar llamada estratégica" },
      secondaryAction: { href: "#catalogue", label: "Explorar sistemas" },
    },
    adaptation: {
      label: "En qué nos diferenciamos",
      headingParts: [
        { text: "Adaptamos el " },
        { text: "sistema al negocio", tone: "accent" },
        { text: ", no el " },
        { text: "negocio al sistema", tone: "counter" },
      ],
      body: "La mayoría del software exige que una empresa trabaje según cómo fue construido. Esto genera costos y fricción diaria. Una caja registradora hecha para un restaurante, puesta en una tienda de comestibles por peso, es el ejemplo más claro.",
      genericTitle: "Un sistema construido para otro",
      genericNote: "Una caja de restaurante en una tienda de comestibles.",
      fittedTitle: "Un sistema construido para usted",
      fittedNote: "El mismo trabajo, adaptado a cómo opera realmente la tienda.",
      unusedLabel: "campos que el personal omite a diario",
      generic: [
        { field: "Número de mesa", verdict: "unused" },
        { field: "Cubiertos por turno", verdict: "unused" },
        { field: "Comanda de cocina", verdict: "unused" },
        { field: "Dividir la cuenta", verdict: "unused" },
        { field: "Stock contado por ración", verdict: "forced" },
        { field: "Precio por artículo", verdict: "kept" },
      ],
      fitted: [
        { field: "Pasillo y estante", verdict: "kept" },
        { field: "Tamaño de cesta", verdict: "kept" },
        { field: "Productos pesados", verdict: "kept" },
        { field: "Precio por peso", verdict: "kept" },
      ],
    },
    customisation: {
      label: "Cómo se entregan",
      headingParts: [
        { text: "Cada sistema se " },
        { text: "adapta", tone: "accent" },
        { text: " antes de ser entregado" },
      ],
      body: "Ninguno de estos llega tal como se muestra aquí. Cada uno se configura según una operación real, lleva la marca propia del cliente y conserva únicamente las funciones que el negocio realmente utiliza.",
      points: [
        "Configurado según la forma en que el negocio ya opera, no al revés",
        "Entregado bajo el nombre e identidad visual propios del cliente",
        "Los módulos innecesarios se eliminan en lugar de simplemente ocultarse",
        "Se amplía cuando la operación requiere algo que el sistema aún no incluye",
      ],
    },
    index: {
      label: "Sistemas de Referencia en Vivo",
      heading: "Sistemas de Ejemplo Construidos para Operaciones Reales",
      description: "Cada sistema que diseñamos está totalmente personalizado, rediseñado y adaptado a las necesidades exactas de su negocio.",
      allLabel: "Todos",
      filterLabel: "Filtrar sistemas por sector",
      singularLabel: "sistema",
      pluralLabel: "sistemas",
      inLabel: "en",
      screensLabel: "pantallas",
    },
    contact: {
      heading: "Véalo aplicado a su propia operación.",
      body: "Cuéntenos cómo opera su empresa hoy y le mostraremos el sistema funcionando con sus datos reales.",
      action: { href: "/#services", label: "Reservar llamada estratégica" },
    },
    detail: {
      breadcrumbHome: "Inicio",
      breadcrumbIndex: "Productos",
      demoLabel: "Ver demostración",
      requestDemoLabel: "Reservar llamada estratégica",
      documentationLabel: "Documentación",
      sections: {
        solves: {
          label: "Qué resuelve",
          heading: "El problema operativo",
        },
        interface: {
          label: "Interfaz",
          heading: "El sistema en uso",
          captureNote: "Las pantallas son capturas del sistema en funcionamiento real.",
          themeLabel: "Temas",
          themeHeading: "Lo que abre su contacto",
          themeNote: "Cada tarjeta se construye según la identidad del cliente.",
          illustrationNote: "Este sistema se muestra con vistas diseñadas de su interfaz.",
        },
        modules: {
          label: "Módulos y características",
          heading: "Qué gestiona",
          body: "Este es el catálogo propio del sistema.",
        },
        replaces: {
          label: "Qué reemplaza",
          heading: "Lo que retira de su mesa de trabajo",
        },
        adapts: {
          label: "Dónde lo adaptamos",
          heading: "Qué se personaliza para usted",
          body: "Estas son las partes que con más frecuencia se adaptan a cada empresa.",
        },
        suits: {
          label: "A quién se dirige",
          heading: "Para qué tipo de negocio está diseñado",
        },
        industriesLabel: "Sectores compatibles",
        integrationsLabel: "Integraciones",
        services: {
          label: "Implementación y soporte",
          heading: "Cómo se entrega este sistema",
          body: "El trabajo alrededor del sistema es un servicio integral.",
        },
      },
      contact: {
        heading: "Véalo con sus propios números.",
        body: "Cuéntenos cómo opera su negocio hoy y le mostraremos el sistema en acción.",
        action: { href: "/#services", label: "Reservar llamada estratégica" },
      },
    },
  },

  ar: {
    breadcrumb: { home: "الرئيسية", current: "المنتجات" },
    hero: {
      label: "أنظمتنا",
      title: "أنظمة تناسب طبيعة عملك",
      emphasis: "تناسب",
      lead: "أنظمة عمل تقوم كامبريدج ماركتينج ببنائها ونشرها وملاءمتها لطريقة عملك الفعلية. افتح أي نظام وستجد أن كل شاشة معروضة هي لقطة حقيقية لنظام قيد التشغيل.",
      primaryAction: { href: "/#services", label: "حجز مكالمة استراتيجية" },
      secondaryAction: { href: "#catalogue", label: "استكشاف الأنظمة" },
    },
    adaptation: {
      label: "كيف نختلف",
      headingParts: [
        { text: "نحن نكيّف " },
        { text: "النظام ليلائم العمل", tone: "accent" },
        { text: "، وليس ", tone: "normal" },
        { text: "العمل ليلائم النظام", tone: "counter" },
      ],
      body: "تطلب معظم البرمجيات من الشركة العمل بالطريقة التي بنيت بها. هذا يسبب ضريبة يومية يدفعها موظفوك. نظام نقاط البيع المخصص لمطعم عند وضعه في متجر يبيع بالوزن هو أوضح مثال على ذلك.",
      genericTitle: "نظام مصمم لشخص آخر",
      genericNote: "نظام مطعم يعمل في متجر بقالة.",
      fittedTitle: "نظام مصمم خصيصاً لك",
      fittedNote: "نفس المهمة، مهيأة تماماً لطريقة عمل المتجر الفعلية.",
      unusedLabel: "حقول يتخطاها الموظفون يومياً",
      generic: [
        { field: "رقم الطاولة", verdict: "unused" },
        { field: "عدد الأفراد للجلسة", verdict: "unused" },
        { field: "تذكرة المطبخ", verdict: "unused" },
        { field: "تقسيم الفاتورة", verdict: "unused" },
        { field: "حساب المخزون بالوجبة", verdict: "forced" },
        { field: "السعر لكل قطعة", verdict: "kept" },
      ],
      fitted: [
        { field: "الممر والرف", verdict: "kept" },
        { field: "حجم السلة", verdict: "kept" },
        { field: "البضائع الموزونة", verdict: "kept" },
        { field: "السعر بالوزن", verdict: "kept" },
      ],
    },
    customisation: {
      label: "طريقة التسليم",
      headingParts: [
        { text: "كل نظام يتم " },
        { text: "تكييفه وتعديله", tone: "accent" },
        { text: " قبل تسليمه للعميل" },
      ],
      body: "لا يتم تسليم أي من هذه الأنظمة بالشكل المعروض هنا فقط. يتم تكوين كل نظام لعمليات حقيقية، ويحمل الهوية التجارية للعميل، ويحتفظ فقط بالأجزاء التي تستخدمها الشركة بالفعل.",
      points: [
        "مهيأ وفقاً لطريقة عمل الشركة الحالية، وليس العكس",
        "يتم تسليمه تحت اسم وهوية العميل الخاصة",
        "تتم إزالة الوحدات غير الضرورية بدلاً من مجرد إخفائها",
        "تتم توسعته وتطويره عندما تتطلب العمليات ميزات إضافية",
      ],
    },
    index: {
      label: "أنظمة مرجعية حية",
      heading: "أنظمة نموذجية مصممة للعمليات الحقيقية",
      description: "كل نظام نقوم بهندسته مخصص بالكامل ومعاد تصميمه ومفصل ليناسب احتياجات عملك بدقة.",
      allLabel: "الكل",
      filterLabel: "تصفية الأنظمة حسب المجال",
      singularLabel: "نظام",
      pluralLabel: "أنظمة",
      inLabel: "في",
      screensLabel: "شاشات",
    },
    contact: {
      heading: "شاهده يعمل وفقاً لعملياتك الخاصة.",
      body: "أخبرنا كيف تدار أعمالك اليوم وسنعرض لك النظام يعمل مع بياناتك الواقعية.",
      action: { href: "/#services", label: "حجز مكالمة استراتيجية" },
    },
    detail: {
      breadcrumbHome: "الرئيسية",
      breadcrumbIndex: "المنتجات",
      demoLabel: "عرض تجريبي",
      requestDemoLabel: "حجز مكالمة استراتيجية",
      documentationLabel: "التوثيق",
      sections: {
        solves: {
          label: "المشكلات التي يعالجها",
          heading: "المشكلة التشغيلية",
        },
        interface: {
          label: "واجهة النظام",
          heading: "النظام قيد الاستخدام",
          captureNote: "الشاشات المعروضة هي لقطات حقيقية من النظام الفعلي.",
          themeLabel: "السمات",
          themeHeading: "ما يراه عميلك",
          themeNote: "كل بطاقة مبنية وفقاً للهوية الخاصة بالعميل.",
          illustrationNote: "تم توضيح هذا النظام برسومات واجهته المخصصة.",
        },
        modules: {
          label: "الوحدات والميزات",
          heading: "ما يديره النظام",
          body: "هذا هو الدليل الخاص بالوحدات المدمجة في النظام.",
        },
        replaces: {
          label: "ما يستبدله النظام",
          heading: "ما يزيله النظام من عبء العمل اليدوي",
        },
        adapts: {
          label: "مجالات التخصيص",
          heading: "ما نقوم بتعديله لأجلك",
          body: "هذه هي الأجزاء الأكثر تخصيصاً لتناسب كل منشأة على حدة.",
        },
        suits: {
          label: "الفئة المستهدفة",
          heading: "النشاط التجاري المناسب",
        },
        industriesLabel: "القطاعات المدعومة",
        integrationsLabel: "عمليات الربط والتكامل",
        services: {
          label: "التنفيذ والدعم المستمر",
          heading: "كيف يتم تقديم هذا النظام",
          body: "العمل المصاحب للنظام يتم كخدمة متكاملة من فريقنا.",
        },
      },
      contact: {
        heading: "شاهده يعمل مع أرقامك الحقيقية.",
        body: "أخبرنا كيف تسير عملياتك وسنوضح لك كيف ينفذها النظام.",
        action: { href: "/#services", label: "حجز مكالمة استراتيجية" },
      },
    },
  },

  si: {
    breadcrumb: { home: "මුල් පිටුව", current: "නිෂ්පාදන" },
    hero: {
      label: "අපගේ පද්ධති",
      title: "ව්යාපාරයට ගැළපෙන පද්ධති",
      emphasis: "ගැළපෙන",
      lead: "Cambridge Marketing විසින් ව්යාපාරයේ සැබෑ මෙහෙයුම් රටාවට ගැළපෙන පරිදි ගොඩනගා ක්‍රියාත්මක කරන සජීවී පද්ධති. ඕනෑම එකක් විවෘත කර බලන්න; සෑම තිරයක්ම සැබෑවටම ධාවනය වන පද්ධතියක සජීවී දර්ශනයකි.",
      primaryAction: { href: "/#services", label: "උපායමාර්ගික සාකච්ඡාවක් වෙන්කරගන්න" },
      secondaryAction: { href: "#catalogue", label: "පද්ධති පරීක්ෂා කරන්න" },
    },
    adaptation: {
      label: "අප වෙනස් වන්නේ කෙසේද",
      headingParts: [
        { text: "අපි " },
        { text: "පද්ධතිය ව්යාපාරයට ගැළපෙන්න සකස් කරමු", tone: "accent" },
        { text: ", " },
        { text: "ව්යාපාරය පද්ධතියට කොටු නොකරමු", tone: "counter" },
      ],
      body: "බොහෝ මෘදුකාංග ව්යාපාරයකට බලකරන්නේ ඒවා ගොඩනගා ඇති රාමුව තුළ වැඩ කිරීමටයි. අවන්හලක් සඳහා සකස් කළ බිල්පත් පද්ධතියක් බර අනුව භාණ්ඩ විකුණන සිල්ලර වෙළඳසැලකට දැමූ විට දෛනිකව විශාල අපහසුතාවයක් ඇතිවේ.",
      genericTitle: "වෙනත් අයෙකු සඳහා ගොඩනැගූ පද්ධතියක්",
      genericNote: "සිල්ලර වෙළඳසැලක ධාවනය වන අවන්හල් බිල්පත් පද්ධතියක්.",
      fittedTitle: "ඔබ වෙනුවෙන්ම සකස් කළ පද්ධතියක්",
      fittedNote: "එම කාර්යයම, වෙළඳසැලේ සැබෑ ක්‍රමයට ගැළපෙන පරිදි සකස් කර ඇත.",
      unusedLabel: "සේවකයින් දිනපතා මඟහරින අනවශ්‍ය දත්ත කොටස්",
      generic: [
        { field: "මේස අංකය", verdict: "unused" },
        { field: "ආසන ගණන", verdict: "unused" },
        { field: "කුස්සියේ ඇණවුම් පත්‍රය", verdict: "unused" },
        { field: "බිල බෙදාගැනීම", verdict: "unused" },
        { field: "කොටස් අනුව තොග ගණනය", verdict: "forced" },
        { field: "භාණ්ඩයක මිල", verdict: "kept" },
      ],
      fitted: [
        { field: "තීරුව සහ රාක්කය", verdict: "kept" },
        { field: "කූඩයේ ප්‍රමාණය", verdict: "kept" },
        { field: "බර අනුව භාණ්ඩ", verdict: "kept" },
        { field: "බර අනුව මිල", verdict: "kept" },
      ],
    },
    customisation: {
      label: "භාරදෙන ආකාරය",
      headingParts: [
        { text: "සෑම පද්ධතියක්ම භාරදීමට පෙර " },
        { text: "අවශ්ය පරිදි සකස් කරනු ලැබේ", tone: "accent" },
        { text: "" },
      ],
      body: "මෙහි පෙන්වා ඇති ආකාරයටම කිසිවක් ලබා නොදේ. සෑම එකක්ම සැබෑ මෙහෙයුම්වලට ගැළපෙන ලෙස සකසා, අපගේ සන්නාමය වෙනුවට පාරිභෝගිකයාගේම අනන්‍යතාවය යටතේ ලබාදෙන අතර ව්යාපාරයට සැබවින්ම අවශ්‍ය කොටස් පමණක් තබා ගනී.",
      points: [
        "ව්යාපාරය දැනටමත් ක්‍රියාත්මක වන ආකාරයට අනුකූලව සකස් කෙරේ",
        "පාරිභෝගිකයාගේම නම සහ සන්නාම අනන්‍යතාවය යටතේ ලබාදේ",
        "අනවශ්‍ය අංග සඟවා තබනවා වෙනුවට සම්පූර්ණයෙන්ම ඉවත් කරනු ලැබේ",
        "ව්යාපාරයට අවශ්‍ය නව අංග ඇත්නම් ඒවා අලුතින් එකතු කෙරේ",
      ],
    },
    index: {
      label: "සජීවී පද්ධති ආදර්ශ",
      heading: "සැබෑ මෙහෙයුම් සඳහා ගොඩනැගූ ආදර්ශ පද්ධති",
      description: "අප විසින් නිර්මාණය කරන සෑම පද්ධතියක්ම ඔබගේ නිශ්චිත ව්යාපාරික අවශ්යතාවන්ට ගැළපෙන පරිදි සම්පූර්ණයෙන්ම වෙනස් කර සකස් කරනු ලැබේ.",
      allLabel: "සියල්ල",
      filterLabel: "ක්ෂේත්‍රය අනුව පද්ධති තෝරන්න",
      singularLabel: "පද්ධතිය",
      pluralLabel: "පද්ධති",
      inLabel: "තුළ",
      screensLabel: "තිර",
    },
    contact: {
      heading: "ඔබගේම මෙහෙයුම් සඳහා මෙය ක්‍රියාත්මක වන අයුරු බලන්න.",
      body: "ඔබගේ ව්යාපාරය අද ක්‍රියාත්මක වන ආකාරය අපට පවසන්න; ඊට අදාළව පද්ධතිය ක්‍රියා කරන අයුරු අපි පෙන්වන්නෙමු.",
      action: { href: "/#services", label: "උපායමාර්ගික සාකච්ඡාවක් වෙන්කරගන්න" },
    },
    detail: {
      breadcrumbHome: "මුල් පිටුව",
      breadcrumbIndex: "නිෂ්පාදන",
      demoLabel: "ආදර්ශනය බලන්න",
      requestDemoLabel: "සාකච්ඡාවක් වෙන්කරගන්න",
      documentationLabel: "ලේඛනගත තොරතුරු",
      sections: {
        solves: {
          label: "විසඳන ගැටළු",
          heading: "මෙහෙයුම් ගැටළුව",
        },
        interface: {
          label: "පද්ධති අතුරුමුහුණත",
          heading: "භාවිතයේ පවතින පද්ධතිය",
          captureNote: "තිර දර්ශන යනු සැබෑ ක්‍රියාකාරී පද්ධතියෙන් ලබාගත් සජීවී දර්ශනයන්ය.",
          themeLabel: "තේමා",
          themeHeading: "පාරිභෝගිකයාට පෙනෙන අතුරුමුහුණත",
          themeNote: "සෑම එකක්ම පාරිභෝගිකයාගේම අනන්‍යතාවයට ගැලපෙන ලෙස නිර්මාණය කෙරේ.",
          illustrationNote: "මෙම පද්ධතිය එහි අතුරුමුහුණතේ රූප සටහන් සහිතව ඉදිරිපත් කර ඇත.",
        },
        modules: {
          label: "අංග සහ විශේෂාංග",
          heading: "පද්ධතිය මගින් පාලනය වන දෑ",
          body: "මෙය මෙම පද්ධතියටම අයත් විශේෂාංග නාමාවලියයි.",
        },
        replaces: {
          label: "පද්ධතිය මඟින් ඉවත් කරන දෑ",
          heading: "අතින් කරන වෙහෙසකර කාර්යයන්ගෙන් නිදහස් වන දෑ",
        },
        adapts: {
          label: "අප වෙනස් කරන අංග",
          heading: "ඔබ වෙනුවෙන් වෙනස් කරනු ලබන දෑ",
          body: "සෑම ව්යාපාරයකටම ගැළපෙන පරිදි වඩාත් බහුලව වෙනස් කරනු ලබන කොටස් මේවාය.",
        },
        suits: {
          label: "වඩාත් ගැළපෙන්නේ කාටද",
          heading: "මෙම පද්ධතිය වඩාත් සුදුසු ව්යාපාර",
        },
        industriesLabel: "සහාය දක්වන ක්ෂේත්‍ර",
        integrationsLabel: "ඒකාබද්ධ කිරීම්",
        services: {
          label: "ක්‍රියාත්මක කිරීම සහ සහාය",
          heading: "මෙම පද්ධතිය භාරදෙන ආකාරය",
          body: "පද්ධතිය ආශ්‍රිත සියලුම සේවාවන් අපගේ විශේෂඥ කණ්ඩායම විසින් සපයනු ලැබේ.",
        },
      },
      contact: {
        heading: "ඔබගේම දත්ත සමඟ මෙය ක්‍රියාත්මක වන අයුරු බලන්න.",
        body: "ඔබගේ ව්යාපාරික අවශ්‍යතා අපට පවසන්න; අපගේ පද්ධතිය ඒ සඳහා ක්‍රියාත්මක වන අයුරු පෙන්වන්නෙමු.",
        action: { href: "/#services", label: "උපායමාර්ගික සාකච්ඡාවක් වෙන්කරගන්න" },
      },
    },
  },

  ta: {
    breadcrumb: { home: "முகப்பு", current: "தயாரிப்புகள்" },
    hero: {
      label: "எங்கள் அமைப்புகள்",
      title: "வணிகத்திற்கு ஏற்றவாறு பொருந்தும் அமைப்புகள்",
      emphasis: "பொருந்தும்",
      lead: "கேம்பிரிட்ஜ் மார்க்கெட்டிங் உங்கள் நிறுவனத்தின் உண்மையான வணிக செயல்பாடுகளுக்கு ஏற்ப கட்டமைத்து வழங்கும் நேரடி இயங்குதள அமைப்புகள். எதையும் திறந்து பாருங்கள்; திரையில் காணும் ஒவ்வொன்றும் இயங்கும் அமைப்பின் நேரடிப் பதிவாகும்.",
      primaryAction: { href: "/#services", label: "வியூக ஆலோசனையை பதிவு செய்க" },
      secondaryAction: { href: "#catalogue", label: "அமைப்புகளை ஆராய்க" },
    },
    adaptation: {
      label: "நாங்கள் எவ்வாறு வேறுபடுகிறோம்",
      headingParts: [
        { text: "நாங்கள் " },
        { text: "அமைப்பை வணிகத்திற்கு ஏற்ப பொருத்துகிறோம்", tone: "accent" },
        { text: ", மாறாக ", tone: "normal" },
        { text: "வணிகத்தை அமைப்பிற்குள் திணிப்பதில்லை", tone: "counter" },
      ],
      body: "பெரும்பாலான மென்பொருட்கள் ஒரு வணிகத்தை அவை கட்டமைக்கப்பட்ட வழியிலேயே இயங்குமாறு கட்டாயப்படுத்துகின்றன. உணவகத்திற்காக உருவாக்கப்பட்ட பில்லிங் முறையை, எடையின் அடிப்படையில் விற்கும் மளிகைக் கடையில் வைத்தால் தினசரி குழப்பமும் தாமதமும் ஏற்படும்.",
      genericTitle: "மற்றொருவருக்காக உருவாக்கப்பட்ட அமைப்பு",
      genericNote: "மளிகைக் கடையில் இயங்கும் உணவக பில்லிங் முறை.",
      fittedTitle: "உங்களுக்காகவே உருவாக்கப்பட்ட அமைப்பு",
      fittedNote: "அதே பணி, கடை எவ்வாறு இயங்குகிறதோ அதற்கு ஏற்ப துல்லியமாக மாற்றியமைக்கப்பட்டது.",
      unusedLabel: "பணியாளர்கள் தினமும் தவிர்க்கும் தேவையற்ற புலங்கள்",
      generic: [
        { field: "மேஜை எண்", verdict: "unused" },
        { field: "அமர்வுக்கு நபர்கள்", verdict: "unused" },
        { field: "சமையலறை குறிப்பு", verdict: "unused" },
        { field: "பில் பிரிப்பு", verdict: "unused" },
        { field: "பகுதி வாரியாக இருப்பு", verdict: "forced" },
        { field: "பொருள் வாரியான விலை", verdict: "kept" },
      ],
      fitted: [
        { field: "நடைபாதை மற்றும் அடுக்கு", verdict: "kept" },
        { field: "கூடை அளவு", verdict: "kept" },
        { field: "எடை பொருட்கள்", verdict: "kept" },
        { field: "எடை வாரியான விலை", verdict: "kept" },
      ],
    },
    customisation: {
      label: "வழங்கப்படும் முறை",
      headingParts: [
        { text: "ஒவ்வொரு அமைப்பும் ஒப்படைக்கப்படுவதற்கு முன் " },
        { text: "முழுமையாக மாற்றியமைக்கப்படுகிறது", tone: "accent" },
        { text: "" },
      ],
      body: "இங்கு காட்டப்பட்டுள்ளவாறு மட்டுமே எதுவும் வழங்கப்படுவதில்லை. ஒவ்வொன்றும் உண்மையான செயல்பாடுகளுக்கு ஏற்ப கட்டமைக்கப்பட்டு, வாடிக்கையாளரின் சொந்த வர்த்தக அடையாளத்துடன், வணிகத்திற்கு தேவையான அம்சங்களுடன் மட்டுமே வழங்கப்படுகிறது.",
      points: [
        "வணிகம் ஏற்கனவே செயல்படும் முறைக்கு ஏற்ப கட்டமைக்கப்படுகிறது",
        "வாடிக்கையாளரின் சொந்த பெயர் மற்றும் வர்த்தக அடையாளத்தின் கீழ் வழங்கப்படுகிறது",
        "தேவையற்ற தொகுதிகள் மறைக்கப்படாமல் முழுமையாக நீக்கப்படுகின்றன",
        "செயல்பாடுகளுக்கு தேவையான புதிய வசதிகள் இருந்தால் புதிதாக இணைக்கப்படுகின்றன",
      ],
    },
    index: {
      label: "நேரடி மாதிரி அமைப்புகள்",
      heading: "உண்மையான செயல்பாடுகளுக்காக உருவாக்கப்பட்ட மாதிரி அமைப்புகள்",
      description: "நாங்கள் உருவாக்கும் ஒவ்வொரு அமைப்பும் உங்கள் வணிகத் தேவைகளுக்கு ஏற்ப முழுமையாகத் தனிப்பயனாக்கப்பட்டு வடிவமைக்கப்படுகிறது.",
      allLabel: "அனைத்தும்",
      filterLabel: "துறை வாரியாக வடிகட்டுக",
      singularLabel: "அமைப்பு",
      pluralLabel: "அமைப்புகள்",
      inLabel: "இல்",
      screensLabel: "திரைகள்",
    },
    contact: {
      heading: "உங்கள் சொந்த செயல்பாடுகளுடன் இது இயங்குவதைக் காண்க.",
      body: "உங்கள் வணிகம் எவ்வாறு இயங்குகிறது என்பதை எங்களிடம் கூறுங்கள்; அதற்கேற்ப இந்த அமைப்பு செயல்படுவதை நாங்கள் காண்பிக்கிறோம்.",
      action: { href: "/#services", label: "வியூக ஆலோசனையை பதிவு செய்க" },
    },
    detail: {
      breadcrumbHome: "முகப்பு",
      breadcrumbIndex: "தயாரிப்புகள்",
      demoLabel: "டெமோ காண்க",
      requestDemoLabel: "வியூக ஆலோசனையை பதிவு செய்க",
      documentationLabel: "ஆவணங்கள்",
      sections: {
        solves: {
          label: "தீர்க்கும் சிக்கல்கள்",
          heading: "செயல்பாட்டு சிக்கல்",
        },
        interface: {
          label: "பயனர் இடைமுகம்",
          heading: "பயன்பாட்டில் உள்ள அமைப்பு",
          captureNote: "காட்டப்படும் திரைகள் நேரடி இயங்குதளத்தின் உண்மையான பதிவுகளாகும்.",
          themeLabel: "தீம்கள்",
          themeHeading: "உங்கள் தொடர்பாளர் காண்பது",
          themeNote: "ஒவ்வொரு அட்டையும் வாடிக்கையாளரின் சொந்த அடையாளத்திற்கு ஏற்ப வடிவமைக்கப்படுகிறது.",
          illustrationNote: "இந்த அமைப்பு அதன் இடைமுகத்தின் விளக்கப் படங்களுடன் காட்டப்பட்டுள்ளது.",
        },
        modules: {
          label: "தொகுதிகள் மற்றும் வசதிகள்",
          heading: "அமைப்பு நிர்வகிக்கும் அம்சங்கள்",
          body: "இது இந்த அமைப்பிற்குரிய தனித்துவமான அம்சங்களின் பட்டியலாகும்.",
        },
        replaces: {
          label: "மாற்றியமைக்கும் பழைய முறைகள்",
          heading: "அலுவலக மேசையிலிருந்து நீக்கப்படும் பழைய வேலைகள்",
        },
        adapts: {
          label: "நாங்கள் மாற்றியமைக்கும் இடங்கள்",
          heading: "உங்களுக்காக மாற்றப்படும் அம்சங்கள்",
          body: "ஒவ்வொரு நிறுவனத்திற்கும் ஏற்ப அதிகம் மாற்றியமைக்கப்படும் பகுதிகள் இவை.",
        },
        suits: {
          label: "யாருக்கு ஏற்றது",
          heading: "இந்த அமைப்புக்கு பொருத்தமான வணிகம்",
        },
        industriesLabel: "ஆதரிக்கப்படும் தொழில்துறைகள்",
        integrationsLabel: "இணைப்புகள்",
        services: {
          label: "செயல்படுத்தல் மற்றும் ஆதரவு",
          heading: "இந்த அமைப்பு வழங்கப்படும் முறை",
          body: "அமைப்பு சார்ந்த அனைத்து பணிகளும் எங்கள் குழுவின் முழுமையான சேவையாக வழங்கப்படும்.",
        },
      },
      contact: {
        heading: "உங்கள் சொந்த எண்களுடன் இதை ஒப்பிட்டுப் பாருங்கள்.",
        body: "உங்கள் வணிகம் இன்று எவ்வாறு இயங்குகிறது என்பதைப் பகிருங்கள்; அதற்கான நேரடி தீர்வை நாங்கள் காண்பிக்கிறோம்.",
        action: { href: "/#services", label: "வியூக ஆலோசனையை பதிவு செய்க" },
      },
    },
  },
};

export const getProductsPageContent = (lang = "en") => {
  return I18N_PRODUCTS_PAGE[lang] || I18N_PRODUCTS_PAGE.en;
};

export const productsIndexContent = I18N_PRODUCTS_PAGE.en;
