/**
 * Interface captures per product.
 * Formats:
 * - `wide`: full-window admin capture, stacks full width
 * - `panel`: smaller composite centered at native width
 * - `portrait`: phone screen in horizontal snap gallery (CAMBCARD)
 */

export const productScreens = {
  "hostel-management": [
    {
      src: "/assets/catalogue/hostel-management/01.webp",
      caption: "Add a room",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/02.webp",
      caption: "Add a tenant",
      width: 1440,
      height: 1260,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/03.webp",
      caption: "All invoices",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/04.webp",
      caption: "Utility bills",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/05.webp",
      caption: "Log a complaint",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/06.webp",
      caption: "Lease monitor",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/07.webp",
      caption: "Staff and roles",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/08.webp",
      caption: "Yearly account",
      width: 1440,
      height: 960,
      format: "wide",
    },
  ],
  "property-management": [
    {
      src: "/assets/catalogue/property-management/01.webp",
      caption: "Dashboard",
      width: 1440,
      height: 753,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/02.webp",
      caption: "Properties",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/03.webp",
      caption: "Property detail",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/04.webp",
      caption: "Tenants",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/05.webp",
      caption: "Invoices",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/06.webp",
      caption: "Units",
      width: 1440,
      height: 810,
      format: "wide",
    },
  ],
  "learning-management": [
    {
      src: "/assets/catalogue/learning-management/01.webp",
      caption: "Assignment submission",
      width: 984,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/learning-management/02.webp",
      caption: "Course discussion",
      width: 984,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/learning-management/03.webp",
      caption: "Certificate",
      width: 1440,
      height: 647,
      format: "panel",
    },
  ],
  "customer-relationship-management": [
    {
      src: "/assets/catalogue/customer-relationship-management/01.webp",
      caption: "Dashboard: income against expenses",
      width: 970,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/customer-relationship-management/02.webp",
      caption: "Project progress",
      width: 1054,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/customer-relationship-management/03.webp",
      caption: "Tasks",
      width: 970,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/customer-relationship-management/04.webp",
      caption: "Clients",
      width: 970,
      height: 600,
      format: "panel",
    },
  ],
  "travel-booking": [
    {
      src: "/assets/catalogue/travel-booking/01.webp",
      caption: "Pricing, person types and availability",
      width: 1440,
      height: 1192,
      format: "wide",
    },
    {
      src: "/assets/catalogue/travel-booking/02.webp",
      caption: "Menu builder",
      width: 1440,
      height: 861,
      format: "wide",
    },
    {
      src: "/assets/catalogue/travel-booking/03.webp",
      caption: "Page and template builder",
      width: 1440,
      height: 795,
      format: "wide",
    },
    {
      src: "/assets/catalogue/travel-booking/04.webp",
      caption: "Theme options",
      width: 1363,
      height: 723,
      format: "wide",
    },
  ],
  "gym-management": [
    {
      src: "/assets/catalogue/gym-management/01.webp",
      caption: "Dashboard: income against expenses",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/02.webp",
      caption: "Trainers",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/03.webp",
      caption: "Classes",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/04.webp",
      caption: "Invoice detail",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/05.webp",
      caption: "Expenses",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/06.webp",
      caption: "Attendance",
      width: 1440,
      height: 810,
      format: "wide",
    },
  ],
  "parking-management": [
    {
      src: "/assets/catalogue/parking-management/01.webp",
      caption: "Dashboard: slots and income flow",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/02.webp",
      caption: "Parking",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/03.webp",
      caption: "Parking zones",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/04.webp",
      caption: "Parking detail",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/05.webp",
      caption: "Parking slots",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/06.webp",
      caption: "Roles and permissions",
      width: 1440,
      height: 810,
      format: "wide",
    },
  ],
  "school-management": [
    {
      src: "/assets/catalogue/school-management/01.webp",
      caption: "Students, added singly or in bulk",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/02.webp",
      caption: "Staff and roles",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/03.webp",
      caption: "Attendance",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/04.webp",
      caption: "Timetable",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/05.webp",
      caption: "Exams and marks",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/06.webp",
      caption: "Fees",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/07.webp",
      caption: "Announcements",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/08.webp",
      caption: "What a parent and a student see",
      width: 800,
      height: 700,
      format: "panel",
    },
  ],
  cambcard: [
    {
      src: "/assets/catalogue/cambcard/01.webp",
      caption: "Fitness and personal training",
      width: 576,
      height: 1461,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/02.webp",
      caption: "Clinics and practitioners",
      width: 576,
      height: 1505,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/03.webp",
      caption: "Events and hospitality",
      width: 576,
      height: 1452,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/04.webp",
      caption: "Salons and studios",
      width: 576,
      height: 1450,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/05.webp",
      caption: "Legal and professional services",
      width: 576,
      height: 1449,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/06.webp",
      caption: "Technology and development",
      width: 576,
      height: 1449,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/07.webp",
      caption: "Design and creative",
      width: 576,
      height: 1489,
      format: "portrait",
    },
  ],
};

export const I18N_SCREEN_CAPTIONS = {
  es: {
    "Add a room": "Añadir habitación",
    "Add a tenant": "Añadir inquilino",
    "All invoices": "Todas las facturas",
    "Utility bills": "Facturas de suministros",
    "Log a complaint": "Registrar reclamo",
    "Lease monitor": "Control de contratos",
    "Staff and roles": "Personal y permisos",
    "Yearly account": "Balance anual",
    "Dashboard": "Panel de control",
    "Properties": "Inmuebles",
    "Property detail": "Detalle del inmueble",
    "Tenants": "Inquilinos",
    "Invoices": "Facturas",
    "Units": "Unidades",
    "Assignment submission": "Entrega de tareas",
    "Course discussion": "Foro del curso",
    "Certificate": "Certificado",
    "Dashboard: income against expenses": "Panel: ingresos frente a gastos",
    "Project progress": "Progreso del proyecto",
    "Tasks": "Tareas",
    "Clients": "Clientes",
    "Pricing, person types and availability": "Precios, tipos de viajero y disponibilidad",
    "Menu builder": "Gestor de menús",
    "Page and template builder": "Gestor de páginas y plantillas",
    "Theme options": "Opciones de diseño",
    "Trainers": "Entrenadores",
    "Classes": "Clases",
    "Invoice detail": "Detalle de factura",
    "Expenses": "Gastos",
    "Attendance": "Control de asistencia",
    "Dashboard: slots and income flow": "Panel: plazas y flujo de ingresos",
    "Parking": "Aparcamiento",
    "Parking zones": "Zonas de aparcamiento",
    "Parking detail": "Detalle de estancia",
    "Parking slots": "Plazas de aparcamiento",
    "Roles and permissions": "Roles y permisos",
    "Students, added singly or in bulk": "Alumnos: registro individual o masivo",
    "Timetable": "Horarios lectivos",
    "Exams and marks": "Exámenes y calificaciones",
    "Fees": "Cuotas y cobros",
    "Announcements": "Avisos y circulares",
    "What a parent and a student see": "Vista para padres y alumnos",
    "Fitness and personal training": "Fitness y entrenamiento personal",
    "Clinics and practitioners": "Clínicas y profesionales de la salud",
    "Events and hospitality": "Eventos y hostelería",
    "Salons and studios": "Salones de belleza y estudios",
    "Legal and professional services": "Servicios legales y profesionales",
    "Technology and development": "Tecnología y desarrollo",
    "Design and creative": "Diseño y creatividad",
  },
  ar: {
    "Add a room": "إضافة غرفة",
    "Add a tenant": "إضافة مستأجر",
    "All invoices": "جميع الفواتير",
    "Utility bills": "فواتير الخدمات",
    "Log a complaint": "تسجيل بلاغ صيانة",
    "Lease monitor": "مراقبة العقود",
    "Staff and roles": "الموظفون والصلاحيات",
    "Yearly account": "الحساب السنوي",
    "Dashboard": "لوحة التحكم",
    "Properties": "العقارات",
    "Property detail": "تفاصيل العقار",
    "Tenants": "المستأجرون",
    "Invoices": "الفواتير",
    "Units": "الوحدات",
    "Assignment submission": "تسليم الواجبات",
    "Course discussion": "نقاشات الدورة",
    "Certificate": "الشهادة",
    "Dashboard: income against expenses": "لوحة التحكم: الإيرادات مقابل المصروفات",
    "Project progress": "تقدم المشروع",
    "Tasks": "المهام",
    "Clients": "العملاء",
    "Pricing, person types and availability": "الأسعار وفئات المسافرين والتوافر",
    "Menu builder": "منشئ القوائم",
    "Page and template builder": "منشئ الصفحات والقوالب",
    "Theme options": "خيارات التصميم",
    "Trainers": "المدربون",
    "Classes": "الحصص التدريبية",
    "Invoice detail": "تفاصيل الفاتورة",
    "Expenses": "المصروفات",
    "Attendance": "تسجيل الحضور",
    "Dashboard: slots and income flow": "لوحة التحكم: المواقف وتدفق الإيرادات",
    "Parking": "المواقف",
    "Parking zones": "مناطق المواقف",
    "Parking detail": "تفاصيل الوقوف",
    "Parking slots": "أماكن الوقوف",
    "Roles and permissions": "الصلاحيات والأدوار",
    "Students, added singly or in bulk": "الطلاب: إضافة فردية أو جماعية",
    "Timetable": "الجدول الدراسي",
    "Exams and marks": "الاختبارات والدرجات",
    "Fees": "الرسوم المدرسية",
    "Announcements": "الإعلانات والتعاميم",
    "What a parent and a student see": "ما يراه ولي الأمر والطالب",
    "Fitness and personal training": "اللياقة والتدريب الشخصي",
    "Clinics and practitioners": "العيادات والممارسون الصحيون",
    "Events and hospitality": "الفعاليات والضيافة",
    "Salons and studios": "صالونات التجميل والاستوديوهات",
    "Legal and professional services": "الخدمات القانونية والمهنية",
    "Technology and development": "التكنولوجيا والتطوير",
    "Design and creative": "التصميم والإبداع",
  },
  si: {
    "Add a room": "කාමරයක් එක් කිරීම",
    "Add a tenant": "නේවාසිකයෙකු එක් කිරීම",
    "All invoices": "සියලුම බිල්පත්",
    "Utility bills": "උපයෝගිතා බිල්පත්",
    "Log a complaint": "පැමිණිල්ලක් සටහන් කිරීම",
    "Lease monitor": "ගිවිසුම් නිරීක්ෂණය",
    "Staff and roles": "කාර්ය මණ්ඩලය සහ භූමිකා",
    "Yearly account": "වාර්ෂික ගිණුම්",
    "Dashboard": "ප්‍රධාන පුවරුව",
    "Properties": "දේපළ",
    "Property detail": "දේපළ විස්තර",
    "Tenants": "නේවාසිකයින්",
    "Invoices": "බිල්පත්",
    "Units": "ඒකක",
    "Assignment submission": "පැවරුම් භාරදීම",
    "Course discussion": "පාඨමාලා සාකච්ඡා",
    "Certificate": "සහතිකය",
    "Dashboard: income against expenses": "ප්‍රධාන පුවරුව: ආදායම් සහ වියදම්",
    "Project progress": "ව්‍යාපෘති ප්‍රගතිය",
    "Tasks": "කාර්යයන්",
    "Clients": "ගනුදෙනුකරුවන්",
    "Pricing, person types and availability": "මිල ගණන් සහ ලබාගත හැකි වේලාවන්",
    "Menu builder": "මෙනු සකසනය",
    "Page and template builder": "පිටු සහ ආකෘති සකසනය",
    "Theme options": "තේමා විකල්ප",
    "Trainers": "පුහුණුකරුවන්",
    "Classes": "පන්ති",
    "Invoice detail": "බිල්පත් විස්තර",
    "Expenses": "වියදම්",
    "Attendance": "පැමිණීම",
    "Dashboard: slots and income flow": "ප්‍රධාන පුවරුව: ඉඩකඩ සහ ආදායම",
    "Parking": "නැවතුම්පොළ",
    "Parking zones": "නැවතුම් කලාප",
    "Parking detail": "නැවතුම් විස්තර",
    "Parking slots": "නැවතුම් ස්ථාන",
    "Roles and permissions": "භූමිකා සහ අවසර",
    "Students, added singly or in bulk": "සිසුන්: තනි හෝ කණ්ඩායම් ලියාපදිංචිය",
    "Timetable": "කාලසටහන",
    "Exams and marks": "විභාග සහ ලකුණු",
    "Fees": "ගාස්තු",
    "Announcements": "නිවේදන",
    "What a parent and a student see": "දෙමාපියන්ට සහ සිසුන්ට පෙනෙන අතුරුමුහුණත",
    "Fitness and personal training": "ක්‍රීඩා සහ ශාරීරික පුහුණු",
    "Clinics and practitioners": "සායන සහ වෛද්‍ය වෘත්තිකයින්",
    "Events and hospitality": "උත්සව සහ සත්කාරක සේවා",
    "Salons and studios": "රූපලාවණ්‍යාගාර සහ ස්ටූඩියෝ",
    "Legal and professional services": "නීතිමය සහ වෘත්තීය සේවා",
    "Technology and development": "තාක්ෂණය සහ මෘදුකාංග",
    "Design and creative": "නිර්මාණකරණය සහ කලාව",
  },
  ta: {
    "Add a room": "அறை சேர்த்தல்",
    "Add a tenant": "வாடகைதாரர் சேர்த்தல்",
    "All invoices": "அனைத்து ரசீதுகள்",
    "Utility bills": "பயன்பாட்டுக் கட்டணங்கள்",
    "Log a complaint": "புகார் பதிவு செய்தல்",
    "Lease monitor": "குத்தகை கண்காணிப்பு",
    "Staff and roles": "பணியாளர்கள் மற்றும் பொறுப்புகள்",
    "Yearly account": "வருடாந்திர கணக்கு",
    "Dashboard": "முதன்மை கட்டுப்பாட்டுப் பலகை",
    "Properties": "சொத்துக்கள்",
    "Property detail": "சொத்து விவரங்கள்",
    "Tenants": "வாடகைதாரர்கள்",
    "Invoices": "ரசீதுகள்",
    "Units": "அலகுகள்",
    "Assignment submission": "ஒப்படைப்பு சமர்ப்பித்தல்",
    "Course discussion": "கலந்துரையாடல் மன்றம்",
    "Certificate": "சான்றிதழ்",
    "Dashboard: income against expenses": "டாஷ்போர்டு: வருமானம் மற்றும் செலவுகள்",
    "Project progress": "திட்ட முன்னேற்றம்",
    "Tasks": "பணிகள்",
    "Clients": "வாடிக்கையாளர்கள்",
    "Pricing, person types and availability": "விலை நிர்ணயம் மற்றும் இருப்பு",
    "Menu builder": "மெனு வடிவமைப்பாளர்",
    "Page and template builder": "பக்க வடிவமைப்பு",
    "Theme options": "வடிவமைப்பு தேர்வுகள்",
    "Trainers": "பயிற்சியாளர்கள்",
    "Classes": "வகுப்புகள்",
    "Invoice detail": "ரசீது விவரம்",
    "Expenses": "செலவுகள்",
    "Attendance": "வருகைப்பதிவு",
    "Dashboard: slots and income flow": "டாஷ்போர்டு: இடங்கள் மற்றும் வருமானம்",
    "Parking": "பார்க்கிங்",
    "Parking zones": "பார்க்கிங் மண்டலங்கள்",
    "Parking detail": "பார்க்கிங் விபரம்",
    "Parking slots": "பார்க்கிங் இடங்கள்",
    "Roles and permissions": "பொறுப்புகள் மற்றும் அனுமதிகள்",
    "Students, added singly or in bulk": "மாணவர்கள்: சேர்க்கை விபரம்",
    "Timetable": "கால அட்டவணை",
    "Exams and marks": "தேர்வுகள் மற்றும் மதிப்பெண்கள்",
    "Fees": "கல்விக் கட்டணங்கள்",
    "Announcements": "அறிவிப்புகள்",
    "What a parent and a student see": "பெற்றோர் மற்றும் மாணவர் காணும் திரை",
    "Fitness and personal training": "உடற்தகுதி மற்றும் தனிப்பயிற்சி",
    "Clinics and practitioners": "மருத்துவமனைகள் மற்றும் மருத்துவர்கள்",
    "Events and hospitality": "நிகழ்வுகள் மற்றும் விருந்தோம்பல்",
    "Salons and studios": "அழகு நிலையங்கள் மற்றும் ஸ்டுடியோக்கள்",
    "Legal and professional services": "சட்ட மற்றும் தொழில்முறை சேவைகள்",
    "Technology and development": "தொழில்நுட்பம் மற்றும் மென்பொருள்",
    "Design and creative": "வடிவமைப்பு மற்றும் படைப்பாற்றல்",
  },
};

export function getProductScreens(slug, lang = "en") {
  const base = productScreens[slug] || [];
  if (!lang || lang === "en" || !I18N_SCREEN_CAPTIONS[lang]) {
    return base;
  }
  const dict = I18N_SCREEN_CAPTIONS[lang];
  return base.map((screen) => ({
    ...screen,
    caption: dict[screen.caption] || screen.caption,
  }));
}
