/**
 * Interface captures per product.
 * Formats:
 * - `wide`: full-window admin capture, stacks full width
 * - `panel`: smaller composite centered at native width
 * - `portrait`: phone screen in horizontal snap gallery (CAMBCARD)
 */

export const productScreens = {
  "hostel-management": [
    {
      src: "/assets/catalogue/hostel-management/01.webp",
      caption: "Add a room",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/02.webp",
      caption: "Add a tenant",
      width: 1440,
      height: 1260,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/03.webp",
      caption: "All invoices",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/04.webp",
      caption: "Utility bills",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/05.webp",
      caption: "Log a complaint",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/06.webp",
      caption: "Lease monitor",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/07.webp",
      caption: "Staff and roles",
      width: 1440,
      height: 960,
      format: "wide",
    },
    {
      src: "/assets/catalogue/hostel-management/08.webp",
      caption: "Yearly account",
      width: 1440,
      height: 960,
      format: "wide",
    },
  ],
  "property-management": [
    {
      src: "/assets/catalogue/property-management/01.webp",
      caption: "Dashboard",
      width: 1440,
      height: 753,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/02.webp",
      caption: "Properties",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/03.webp",
      caption: "Property detail",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/04.webp",
      caption: "Tenants",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/05.webp",
      caption: "Invoices",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/property-management/06.webp",
      caption: "Units",
      width: 1440,
      height: 810,
      format: "wide",
    },
  ],
  "learning-management": [
    {
      src: "/assets/catalogue/learning-management/01.webp",
      caption: "Assignment submission",
      width: 984,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/learning-management/02.webp",
      caption: "Course discussion",
      width: 984,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/learning-management/03.webp",
      caption: "Certificate",
      width: 1440,
      height: 647,
      format: "panel",
    },
  ],
  "customer-relationship-management": [
    {
      src: "/assets/catalogue/customer-relationship-management/01.webp",
      caption: "Dashboard: income against expenses",
      width: 970,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/customer-relationship-management/02.webp",
      caption: "Project progress",
      width: 1054,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/customer-relationship-management/03.webp",
      caption: "Tasks",
      width: 970,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/customer-relationship-management/04.webp",
      caption: "Clients",
      width: 970,
      height: 600,
      format: "panel",
    },
  ],
  "travel-booking": [
    {
      src: "/assets/catalogue/travel-booking/01.webp",
      caption: "Pricing, person types and availability",
      width: 1440,
      height: 1192,
      format: "wide",
    },
    {
      src: "/assets/catalogue/travel-booking/02.webp",
      caption: "Menu builder",
      width: 1440,
      height: 861,
      format: "wide",
    },
    {
      src: "/assets/catalogue/travel-booking/03.webp",
      caption: "Page and template builder",
      width: 1440,
      height: 795,
      format: "wide",
    },
    {
      src: "/assets/catalogue/travel-booking/04.webp",
      caption: "Theme options",
      width: 1363,
      height: 723,
      format: "wide",
    },
  ],
  "gym-management": [
    {
      src: "/assets/catalogue/gym-management/01.webp",
      caption: "Dashboard: income against expenses",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/02.webp",
      caption: "Trainers",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/03.webp",
      caption: "Classes",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/04.webp",
      caption: "Invoice detail",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/05.webp",
      caption: "Expenses",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/gym-management/06.webp",
      caption: "Attendance",
      width: 1440,
      height: 810,
      format: "wide",
    },
  ],
  "parking-management": [
    {
      src: "/assets/catalogue/parking-management/01.webp",
      caption: "Dashboard: slots and income flow",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/02.webp",
      caption: "Parking",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/03.webp",
      caption: "Parking zones",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/04.webp",
      caption: "Parking detail",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/05.webp",
      caption: "Parking slots",
      width: 1440,
      height: 810,
      format: "wide",
    },
    {
      src: "/assets/catalogue/parking-management/06.webp",
      caption: "Roles and permissions",
      width: 1440,
      height: 810,
      format: "wide",
    },
  ],
  "school-management": [
    {
      src: "/assets/catalogue/school-management/01.webp",
      caption: "Students, added singly or in bulk",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/02.webp",
      caption: "Staff and roles",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/03.webp",
      caption: "Attendance",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/04.webp",
      caption: "Timetable",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/05.webp",
      caption: "Exams and marks",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/06.webp",
      caption: "Fees",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/07.webp",
      caption: "Announcements",
      width: 800,
      height: 600,
      format: "panel",
    },
    {
      src: "/assets/catalogue/school-management/08.webp",
      caption: "What a parent and a student see",
      width: 800,
      height: 700,
      format: "panel",
    },
  ],
  cambcard: [
    {
      src: "/assets/catalogue/cambcard/01.webp",
      caption: "Fitness and personal training",
      width: 576,
      height: 1461,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/02.webp",
      caption: "Clinics and practitioners",
      width: 576,
      height: 1505,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/03.webp",
      caption: "Events and hospitality",
      width: 576,
      height: 1452,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/04.webp",
      caption: "Salons and studios",
      width: 576,
      height: 1450,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/05.webp",
      caption: "Legal and professional services",
      width: 576,
      height: 1449,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/06.webp",
      caption: "Technology and development",
      width: 576,
      height: 1449,
      format: "portrait",
    },
    {
      src: "/assets/catalogue/cambcard/07.webp",
      caption: "Design and creative",
      width: 576,
      height: 1489,
      format: "portrait",
    },
  ],
};
